config/routes.rb
EchoFriend::Application.routes.draw do
  get "user/index"
  resources :user do 
   collection do
     get 'index'
    
   end
  member do
    get 'userprofile'
    get 'addfriend'
   
  end

  end
  resources :wall
  resources :login do
    member do
     get 'logout'
    end
   collection do 
     post'dologin'
    end
  end

  resources :friendrequest do
    
    member do
     get 'all_suggess_friends'
     get 'addfriend'
     get 'add_friend_into_list'
    end
  end

  resources :photo do
    member do
      post 'post_photo'
    end
  end 
  resources :wall_like do
    member do
       get 'likepost'
     end
   end

  root :to => 'user#index'

end

app/models/user.rb
class User < ActiveRecord::Base
 has_many :wall_likes
 has_many :walls
 has_many :friendrequests
 has_many :friend_added_lists
  has_attached_file :avatar, :default_url => '/q.png', :styles => { :medium => "300x300>", :thumb => "100x100>" }
  attr_accessible :city, :country, :email_id, :mobile, :password, :state, :user_name,:password_confirmation
  attr_accessible :images,:avatar
  validates :city,:country, :email_id, :password, :state, :user_name, :presence=>true
  validates :password, :confirmation => true
  validates :password_confirmation, :presence => true
  validates :mobile, :numericality=>{:only_integer=>true}

end

app/controllers/user_controller.rb
class UserController < ApplicationController
  before_filter :check_session, :only=>[:userprofile,:edit,:update]
 
  def index
  end

  def new
    @user = User.new
  end

  def create
    @users = User.new(params[:user])
    if @users.save
      session[:user_id]=@users.email_id
      redirect_to userprofile_user_path(@users.id)
    else
      redirect_to new_user_path
    end
  end
  def userprofile
    @user=User.find(params[:id])
    @friend_request_id = Friendrequest.select("user_id").where(:friend_id=>@user.id , :status=>"pending")
    @friend_request_name = User.where(:id => @friend_request_id.map{|s| s.user_id}) # pending request 
    @friends = @user.friendrequests.select("friend_id").where(:status =>"accepted")
    friends = @friends.map{|s| s.friend_id}
    @friendss = Friendrequest.select("user_id").where(:friend_id=>params[:id], :status =>"accepted")
    friendss = @friendss.map{|s| s.user_id}
    c = friends + friendss
    @friends_lists = User.find(:all, :conditions => ['id not in (?)',c]) #find all friend list except current_user
    if @friends_lists.blank?
       @friends_lists = User.find(:all, :conditions => ['id not in (?)', @user.id])
    end
      @friends = @user.friendrequests.select("friend_id").where(:status =>"accepted")
      friends = @friends.map{|s| s.friend_id}
      @friendss = Friendrequest.select("user_id").where(:friend_id=>params[:id], :status =>"accepted")
      friendss = @friendss.map{|s| s.user_id}
      c = friends + friendss
      @friend_added_name=User.where(:id => c)
      abc = c << params[:id].to_i # all joined friend id
      @wall_user_id = Wall.find(:all)
      walls = @wall_user_id.map{|s| s.user_id}
      @hash = Hash.new
      for i in 0...abc.length
        wall = Wall.where(:user_id => abc[i]) # find all user_id from wall model
        unless wall.blank? #check
          for j in 0...wall.length  
            walllike = WallLike.where(:user_id => abc[i],:wall_id=>wall[j].id)
            if walllike.blank?
             # @hash[User.where(:id=>abc[i])]= {"#{wall[j].post_wall}"=>{"#{wall[j].id}"=>"like"}}
#######################################
# <% @hash.each do |key,value| %>
   #  <%= key[0].user_name %>  
   #  <% value.each do |v,id| %><%= v %>   
    # <% id.each do |x,y| %>
     #<%= link_to "#{y}", likepost_wall_like_path(x) %> <p>
     # <% end %>
     # <% end %>
     #<% end %>

               else
             # @hash[User.where(:id=>abc[i])]= {"#{wall[j].post_wall}"=>{"#{wall[j].id}"=>"unlike"}}
            end
           end
        end
      end
      
  end
  

  #edit profile
  def edit
    @user = User.find(params[:id])
  end

 #update profile
  def update
    @user = User.find(params[:id])
    @users=User.where(:id=>params[:id])
    session[:user_id]=@users[0].email_id
    if @user.update_attributes(params[:user])
      redirect_to userprofile_user_path(@user.id)
    else
      render edit_user(@user)
    end
  end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/user/_editform.html.erb
<%= form_for @user do |f| %>
  <div class="divTable">
    <div class="divRow">
      <div class="divCell">
        <%= f.label :name %>
      </div>
      <div class="divCell">
        <%= f.text_field :user_name %><br />
      </div>
    </div>

    <div class="divRow">
      <div class="divCell">
        <%= f.label :Email %>
      </div>
      <div class="divCell">
        <%= f.email_field :email_id %>
      </div>
    </div>

   <div class="divRow">
     <div class="divCell">
       <%= f.label :password %>
     </div>
     <div class="divCell">
       <%= f.password_field:password %><br />
     </div>
   </div>

   <div class="divRow">
     <div class="divCell">
       <%= f.label :confirm_password %>
     </div>
     <div class="divCell">
       <%= f.password_field :password_confirmation %><br />
     </div>
   </div>
 
   <div class="divRow">
     <div class="divCell">
       <%= f.label :Mobile %>
     </div>
     <div class="divCell">
       <%= f.text_field :mobile %><br />
     </div>
   </div>

   <div class="divRow">
     <div class="divCell">
       <%= f.label :Country %>
     </div>
     <div class="divCell">
       <%= f.text_field :country %><br />
     </div>
   </div>

   <div class="divRow">
     <div class="divCell">
       <%= f.label :State %>
     </div>
     <div class="divCell">
       <%= f.text_field:state %><br />
     </div>
   </div>
 
   <div class="divRow">
     <div class="divCell">
       <%= f.label :City %>
     </div>
     <div class="divCell">
       <%= f.text_field :city %><br />
     </div>
   </div>
 
   <div class="divRow">
     <div class="divCell">
       <%= f.label :image %>
     </div>
     <div class="divCell">
       <%= f.file_field :avatar %><br />
     </div>
   </div>
  
   <div class="divRow">
     <div class="divCell">&nbsp;
     </div>
     <div class="divCell">
       <%= f.submit %>
     </div>
   </div>
 </div>
<% end %>

app/views/user/_form.html.erb
<div id="post" align ="right">
<%= link_to 'Register', new_user_path %>
<%= form_tag dologin_login_index_path  do %>
<% if flash[:error] %>
<%= flash[:error] %>
<% end %><br />
    <%= label_tag("Email ID") %>
    <%= email_field_tag(:email) %></br>  
    <%= label_tag ("password") %>
    <%= password_field_tag(:password) %></br>
<%= submit_tag("login") %>
<% end %>

 </div>   
 

app/views/user/_registrationform.html.erb
<%= form_for @user, :url => {:action => 'create', :id =>@user.id} do |f| %>

  <% if @user.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited
        this post from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  
<div class="divTable">
  <div class="divRow">
    <div class="divCell">
      <%= f.label :name %>
    </div>
    <div class="divCell">
      <%= f.text_field :user_name %><br />
    </div>
  </div>


  <div class="divRow">
    <div class="divCell">
    <%= f.label :Email %>
    </div>
    <div class="divCell">
    <%= f.email_field :email_id %>
     </div>
  </div>


  <div class="divRow">
    <div class="divCell">
    <%= f.label :password %>
    </div>
    <div class="divCell">
    <%= f.password_field:password %><br />
    </div>
  </div>


  <div class="divRow">
    <div class="divCell">
    <%= f.label :confirm_password %>
   </div>
    <div class="divCell">
    <%= f.password_field:password_confirmation %><br />
  </div>
 </div>
 


  <div class="divRow">
    <div class="divCell">
    <%= f.label :Mobile %>
     </div>
    <div class="divCell">
    <%= f.text_field:mobile %><br />
  </div>
 </div>


  <div class="divRow">
    <div class="divCell">
    <%= f.label :Country %>
    </div>
    <div class="divCell">
    <%= f.text_field:country %><br />
   </div>
 </div>

  

  <div class="divRow">
    <div class="divCell">
    <%= f.label :State %>
  </div>
    <div class="divCell">
    <%= f.text_field:state %><br />
  </div>
 </div>
 

  <div class="divRow">
    <div class="divCell">
    <%= f.label :City %>
  </div>
    <div class="divCell">
    <%= f.text_field:city %><br />
  </div>
 </div>

 
  <div class="divRow">
    <div class="divCell">&nbsp;</div>
    <div class="divCell">
    <%= f.submit %>
  </div>
</div></div>
<% end %>

app/views/user/edit.html.erb
<div id="index_id">
  <div id="img">
    <%= image_tag @user.avatar.url,:size => "170x150" , :alt=>"No image" %>
  </div>
  hello<%= link_to "#{@user.email_id}",userprofile_user_path(@user.id) %> <%= link_to 'logout', logout_login_path(@user) %>
</div>

<div id="left_item">
</div>

<div id="right_item">
</div>

<div id="middle">
  <%= render 'editform' %>
</div>

<div id="footer">
</div>

app/views/user/index.html.erb
<div id="index_id">
 
<%= render 'form' %>

</div>
<div id="left_item">

</div>
<div id="right_item">

</div>
<div id="footer">

</div>

app/views/user/new.html.erb
<div id="index_id">
  
<%= render 'form' %>


</div>
<div id="left_item">

</div>
<div id="right_item">
</div>
<div id="middle">

<%= render 'registrationform' %>
</div>
<div id="footer">

</div>

app/views/user/userprofile.html.erb
      
<div id="index_id">
  <div id="img">
    <%= image_tag @user.avatar.url,:size => "170x150", :alt=>"/home/rajeev_work/echo_friend/q.png" %>
  </div>
    hello <%= link_to "#{@user.email_id}",userprofile_user_path(@user.id) %>  <%= link_to 'edit profile', edit_user_path(@user) %>   <%= link_to 'logout',logout_login_path(@user) %>
</div>

<div id="left_item">
  <div id="added_friend">
    Friend list....
     <% @friend_added_name.each do |friend| %>
       <br /> <%= friend.user_name %>
     <% end %>
  </div>

  <div id="friend_request_name">
       Friend_Request....<p>
    <% @friend_request_name.each do |friend| %>
      <%= friend.user_name %> 
      <%= button_to "Accept", {:controller => :friendrequest,:action => 'add_friend_into_list', :id => friend.id }, :method => :get %>
      <%= button_to "Ignore", {:controller => :friendrequest,:action => 'destroy', :id => friend.id }, :method => :delete %>
      
    <% end %>
  </div> 
</div>

<div id="right_item">
   <%= link_to 'See all friend',all_suggess_friends_friendrequest_path(@user) %></br><p>
   <% @friends_lists.each do |f| %>
      <% if f.email_id == session[:user_id] %>
      <% else  %> 
        <%= f.user_name %><%= link_to 'Add friend', addfriend_friendrequest_path(f.id) %></br>
      <% end %>
   <% end %>
</div>

<div id="middle" >
   <p><%= link_to 'POST', {:controller=>"wall",:action=> 'new'},:remote=>true %></p>
   <div id="postwall"></div><br />
   <div id="postwalls"></div>
  
</div>

<div id="footer">
</div>

<%= javascript_tag do %>
  $("#middle").bind("ajax:complete", function(et, e){
    $("#postwall").html(e.responseText); // insert content
  });
<% end %>
<%= javascript_tag do %>
  $("#new_wall").bind("ajax:complete", function(et, e){
    $("#postwalls").append(e.responseText); // insert content
  });
<% end %>