config/routes.rb
EchoFriend::Application.routes.draw do
  get "user/index"
  resources :user do 
   collection do
     get 'index'
    
   end
  member do
    get 'userprofile'
    get 'addfriend'
   
  end

  end
  resources :wall
  resources :login do
    member do
     get 'logout'
    end
   collection do 
     post'dologin'
    end
  end

  resources :friendrequest do
    
    member do
     get 'all_suggess_friends'
     get 'addfriend'
     get 'add_friend_into_list'
    end
  end

  resources :photo do
    member do
      post 'post_photo'
    end
  end 
  resources :wall_like do
    member do
       get 'likepost'
     end
   end

  root :to => 'user#index'

end

app/models/friendrequest.rb
class Friendrequest < ActiveRecord::Base
  belongs_to :user
  attr_accessible :friend_id, :status
end

app/controllers/friendrequest_controller.rb
class FriendrequestController < ApplicationController
  before_filter :check_session, :only=>[:index,:all_suggess_friends]
  def index
    
  end
  def all_suggess_friends
    @user=User.find(params[:id])
    @friends = @user.friendrequests.select("friend_id").where(:status =>"accepted")
    friends = @friends.map{|s| s.friend_id}
    @friendss = Friendrequest.select("user_id").where(:friend_id=>params[:id], :status =>"accepted")
    friendss = @friendss.map{|s| s.user_id}
    c = friends + friendss 
    @friends_lists = User.find(:all, :conditions => ['id not in (?)',c]) #find all friend list except current_user
    if @friends_lists.blank?
       @friends_lists = User.find(:all, :conditions => ['id not in (?)', @user.id])
    end
  end

  def addfriend 
    @user = User.where(:email_id=> session[:user_id])
    @check_friend = Friendrequest.where(:user_id => @user[0].id, :friend_id => params[:id])
    debugger
    if @check_friend.blank?
       @check_friend_again =Friendrequest.where(:user_id =>params[:id], :friend_id => @user[0].id)     
       if @check_friend_again.blank?
          @friendrequest = Friendrequest.new
          @friendrequest.user_id = @user[0].id
          @friendrequest.friend_id = params[:id]
          @friendrequest.status = "pending"
          if @friendrequest.save
          else
            redirect_to user_index_path
          end
       end    
    end 
      redirect_to  userprofile_user_path(@user[0].id)  
  end
  
  def destroy
    user = User.where(:email_id => session[:user_id])
    friendrequest = Friendrequest.where(:friend_id=>user[0].id,:user_id=>params[:id])
    friendrequest[0].destroy
    redirect_to userprofile_user_path(user[0].id)
  end

  def add_friend_into_list
    @user = User.where(:email_id => session[:user_id])
   # Friendrequest.delete_all(["user_id = ? AND friend_id = ? ", @user[0].id, params[:id]])
    Friendrequest.update_all(["status = ?","accepted"], ["user_id = ? and friend_id = ?", params[:id],@user[0].id]) # update friend request status
    redirect_to userprofile_user_path(@user[0].id)
  end

end

app/helpers/friendrequest_helper.rb
module FriendrequestHelper
end

app/views/friendrequest/all_suggess_friends.html.erb
<div id="index_id">
  <div id="img">
   <%= image_tag @user.avatar.url,:size => "170x150", :alt=>"No image" %>
  </div>
    hello  <%= link_to "#{@user.email_id}",userprofile_user_path(@user.id) %> <%= link_to 'edit profile', edit_user_path(@user) %>   <%= link_to 'logout', logout_login_path(@user) %>
</div>

<div id="left_item">
  <div id="added_friend">
    Friend list....
     
  </div>
  <div id="friend_request_name">
       Friend_Request....<p>
    
  </div> 
</div>

<div id="right_item">
  <%= link_to 'See all friends',all_suggess_friends_friendrequest_path(@user) %></br><p>
   
</div>

<div id="middle"><p>
  <% @friends_lists.each do |f| %>
      <% if f.email_id == session[:user_id] %>
      <% else  %> 
        <%= image_tag f.avatar.url,:size => "50x30", :alt=>"No image" %>&nbsp;&nbsp;&nbsp;&nbsp;<%= f.user_name %><%= button_to "Send Friend Request", {:controller => :friendrequest,:action => 'addfriend', :id => f.id }, :method => :get %>
       
        <p></br>

      <% end %>
   <% end %>
</div>

<div id="footer">
</div>

app/views/friendrequest/index.html.erb
<div id="index_id">
  <div id="img">
  
  </div>
    hello <%= session[:user_id] %>   <%= link_to 'edit profile', edit_user_path(@user) %>   <%= link_to 'logout', logout_login_path(@user) %>
</div>

<div id="left_item">
  Friend list....
     

  <div id="friend_request_name">
       Friend_Request....<p>
    
  </div> 
</div>

<div id="right_item">
   <%= link_to 'Add Friends',friendrequest_path %></br><p>
   
</div>

<div id="middle">
  <% @user.each do |f| %>
      <% if f.email_id == session[:user_id] %>
      <% else  %> 
        <%= f.user_name %></br>
      <% end %>
   <% end %>
</div>

<div id="footer">
</div>